version: '3.9'

services:
  nginx:
    build:
      context: ../
      dockerfile: .docker/nginx.Dockerfile
    image: ${NAME}-nginx:${TAG}
    container_name: ${NAME}-nginx
    restart: always
    volumes:
      - ../:/workdir
      - ./nginx/etc/nginx/conf:/etc/nginx/conf
      - ./nginx/etc/nginx/templates:/etc/nginx/templates
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
      - 443
    ports:
      - 7003:80
      - 7004:81